### ISSUE TITLE
stdout not created for Windows 10

### ISSUE THREAD

**Issue by krshedd** [eriqande/Rrunstruct#1]
Hey Eric, I finally figured out what the issue was with `structure_runs` on my Windows10 machine today. For whatever reason `system2` needed to have both `stdout` and `stderr` pointing to the same file (i.e. "stdoutf"). I forked your repository, made that one change, loaded my forked package, and it worked for whatever reason ([link](https://github.com/krshedd/Rrunstruct/commit/22912155fc1693463af6ef6a9a7d4a32bc7a4ebf)).

I'm not sure if it is worth you making the change in your repository as it may have unintended side effects on other systems (Mac, Linux, older versions of Windows, etc.). Just wanted to let you know.

**Comment by eriqande** [comment]
Thanks Kyle,
I incorporated that change and everything still works on the Mac, so I committed, pushed and closed it.
See you tomorrow!

eric
